### ISSUE TITLE
Showing Value error everytime

### ISSUE THREAD

**Issue by telegrambotdev** [adityathebe/telegramForwarder#10]
The below error is appearing everytime..
db,pytjonbot,nodebot everything is working fine.

this is most probably due to telethon error.can you fix it ? which telethon version you are using ?

`ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f62334f7070>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.   python-agent_1  | [INFO] forwarder.py:50 --`

**Comment by adityathebe** [comment]
what action causes this error ?

**Comment by telegrambotdev** [comment]
> what action causes this error ?
when i run

docker-compose up --build

**Comment by telegrambotdev** [comment]
> what action causes this error ?

i searched the error in web..all i can found is telethon version error

**Comment by adityathebe** [comment]
I just did a fresh clone of the app and was able to run with no errors. Did you create the `.env` file ?

![image](https://user-images.githubusercontent.com/13419481/100735815-ed893e80-33f9-11eb-8da2-219569bf6f91.png)

**Comment by telegrambotdev** [comment]
![IMG_20201201_181251_827](https://user-images.githubusercontent.com/20116017/100742481-de59bf00-3400-11eb-90f1-6ccaa278e7f9.jpg)


bot is working fine..but msgs are not forwarding..when i look on the cmd,i am getting the above error..

when i changed telethon version to `1.9.0` the error log is disappearing,but still messages arent forwarding..this is a great code..but something somewhere wrong..i cant figured that..

**Comment by telegrambotdev** [comment]
yup i also filled .env vars

**Comment by adityathebe** [comment]
Message forwarding are working fine for me. 

Can you make sure that the **agent** account is present in both the entities (source & destination) ?

**Comment by telegrambotdev** [comment]
> Message forwarding are working fine for me.
> 
> Can you make sure that the **agent** account is present in both the entities (source & destination) ?

i will attach screenshot below..as per my calculation,db,python and node bot is up..

the error reffers to telethon..lol i wonder how this works for you

**Comment by telegrambotdev** [comment]
![IMG_20201201_191729_859](https://user-images.githubusercontent.com/20116017/100749196-5bd5fd00-340a-11eb-84b9-3880421313b1.jpg)
![IMG_20201201_191756_327](https://user-images.githubusercontent.com/20116017/100749231-67292880-340a-11eb-9c3c-9453b4b5e48a.jpg)
![IMG_20201201_191732_849](https://user-images.githubusercontent.com/20116017/100749241-6b554600-340a-11eb-8d80-c99c8bf9fbd1.jpg)
![IMG_20201201_191749_769](https://user-images.githubusercontent.com/20116017/100749268-73ad8100-340a-11eb-841f-7ae15f6228bf.jpg)
![IMG_20201201_191926_996](https://user-images.githubusercontent.com/20116017/100749282-7ad48f00-340a-11eb-962b-f21f230af831.jpg)

**Comment by adityathebe** [comment]
> Can you make sure that the **agent** account is present in both the entities (source & destination) ?

I'm not really sure why it's not working for you. Can you verify what I asked before ?

**Comment by telegrambotdev** [comment]
> > Can you make sure that the **agent** account is present in both the entities (source & destination) ?
> 
> I'm not really sure why it's not working for you. Can you verify what I asked before ?

how to verify that..i really dont get that part

**Comment by adityathebe** [comment]
![image](https://user-images.githubusercontent.com/13419481/100766685-0527ed80-3421-11eb-91e9-53e14bef9639.png)

Make sure that the *agent telegram account* is in both of this group/channel

**Comment by telegrambotdev** [comment]
> ![image](https://user-images.githubusercontent.com/13419481/100766685-0527ed80-3421-11eb-91e9-53e14bef9639.png)
> 
> Make sure that the _agent telegram account_ is in both of this group/channel

yup it is..both are in same telegram account

**Comment by telegrambotdev** [comment]
> ![image](https://user-images.githubusercontent.com/13419481/100766685-0527ed80-3421-11eb-91e9-53e14bef9639.png)
> 
> Make sure that the _agent telegram account_ is in both of this group/channel

luckily it Started working.

the error occours the source and destination channels are created by same telegram account.

i tried a different telegram a channel and it worked

**Comment by telegrambotdev** [comment]
Anyway to add redirection without join the channel ?

currently if we add

`/add @test @test2`

our user account automatically joins the `test` channel..instead of that..any way to add bot instead of that ?

**Comment by adityathebe** [comment]
Sorry, that's not possible at the moment and I don't plan to add that feature
