### ISSUE TITLE
How map to TG groups without invite ?

### ISSUE THREAD

**Issue by namz** [adityathebe/telegramForwarder#13]
hi, 

if i dont have invite links for my source telegram group, how would i map it with my destination channel ?
plz advise with an example.

**Comment by adityathebe** [comment]
If the source Telegram group is public then you can just use the username

**Comment by namz** [comment]
> If the source Telegram group is public then you can just use the username

And if its a private group where i am a regular user (not admin) then ?

**Comment by adityathebe** [comment]
The invitation url is mandatory in that case as the agent needs to join the group

**Comment by namz** [comment]
> The invitation url is mandatory in that case as the agent needs to join the group

understood. thank you
