### ISSUE TITLE
Can't add redirect

### ISSUE THREAD

**Issue by ljm1447669873** [adityathebe/telegramForwarder#15]
INFO in server: [/getentity] :: Entity Name @google
python-agent | [ERROR] server.py:87 -- The key is not registered in the system (caused by ResolveUsernameRequest)

**Comment by adityathebe** [comment]
Please make sure you login first

https://github.com/adityathebe/telegramForwarder#post-installation

**Comment by softech98** [comment]
**Building node-bot
Step 1/7 : FROM node:lts-jessie
lts-jessie: Pulling from library/node
ERROR: Service 'node-bot' failed to build: no matching manifest for linux/arm64/v8 in the manifest list entries
**
