### ISSUE TITLE
Building node-bot

### ISSUE THREAD

**Issue by softech98** [adityathebe/telegramForwarder#16]
Building node-bot
Step 1/7 : FROM node:lts-jessie
lts-jessie: Pulling from library/node
ERROR: Service 'node-bot' failed to build: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by adityathebe** [comment]
Looks like the node:lts-jessie is not supported on your system. You can try a different docker image.

**Comment by softech98** [comment]
> Looks like the node:lts-jessie is not supported on your system. You can try a different docker image.

How? 
i am using debian buster armbian linux
![image](https://user-images.githubusercontent.com/31172852/103164640-7ac88300-4840-11eb-84ac-82a9f0d8ab82.png)
