### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by coldfinger80** [adityathebe/telegramForwarder#17]
Thanks for the great script! I have the problem that the filter settings have no effect. The forwarding works perfectly, but the filter has no effect. Filter defined and activated, but no effect. Thanks for the quick help.

**Comment by adityathebe** [comment]
It's probably because the user isn't a "premium user". Please check these lines of code here - https://github.com/adityathebe/telegramForwarder/blob/d8bf0c101bea204a5d43369b87c789658c5dd156/agent/forwarder.py#L61-L79

You can either
- modify the database and make the user a premium user
- modify the code to not perform the check

**Comment by funnyxing** [comment]
> It's probably because the user isn't a "premium user". Please check these lines of code here -
> 
> https://github.com/adityathebe/telegramForwarder/blob/d8bf0c101bea204a5d43369b87c789658c5dd156/agent/forwarder.py#L61-L79
> 
> You can either
> 
> * modify the database and make the user a premium user
> * modify the code to not perform the check

Thanks！
The filter works great！
But I have a new problem：
**I want to merge and forward multiple messages (the source message is merged)
But now it’s a single message forwarding**
I don't know where to modify.
Please
Thanks for the quick help.

**Comment by compunerd4** [comment]
> It's probably because the user isn't a "premium user". Please check these lines of code here -
> 
> https://github.com/adityathebe/telegramForwarder/blob/d8bf0c101bea204a5d43369b87c789658c5dd156/agent/forwarder.py#L61-L79
> 
> You can either
> 
> * modify the database and make the user a premium user
> * modify the code to not perform the check

I tried editing the /agent/forwarder.py code then ran docket-compose up from scratch and it's still asking me to upgrade , I changed it to: 
`if is_user_premium != 1:`  instead but it's still not working.

I'm not sure how to edit the database from docker storage

**Comment by adityathebe** [comment]
@compunerd4 Thanks for pointing that out. I have made some changes and pushed the new code.

- New users are by default premium users. 
- There was a design flaw in filters. I've pushed a temporary fix.

Please pull the new changes and let me know you face any issues

**Comment by compunerd4** [comment]
Awesome thank you, it's working fine now.
