### ISSUE TITLE
Redirect from channel to Private Bot chat

### ISSUE THREAD

**Issue by compunerd4** [adityathebe/telegramForwarder#21]
I have multiple redirections set up successfully scraping multiple feeds into my main channel.
Next I want to setup a new redirect from my channel to another bot I created.

1. Set up a bot (I created a google drive bot)
2. Redirect from channel to bot by using `/add @channel @username_BOT`

These two steps should work but it's not redirecting.

- I have no filters on
- My TelegramForwarder bot is admin of my channel
- My Second bot is a different bot API
- The redirection shows as setup correctly and activate but it just doesn't do anything

**Comment by adityathebe** [comment]
It seems like the agent is the one who is sending the messages to your channel.

If that's the case then it will simple ignore the messages it sent to prevent possible infinite loops.
