### ISSUE TITLE
/activate id no work

### ISSUE THREAD

**Issue by funnyxing** [adityathebe/telegramForwarder#22]
When I add a redirect, I get an error using /activate <redirection id>. 
![Snipaste_2021-02-18_09-44-54](https://user-images.githubusercontent.com/42426015/108291897-02da6180-71ce-11eb-9165-3a57c1bc8cfd.png)
I only had one redirect when I tested the picture above.

> node-bot_1      | {"level":30,"time":1613572796132,"pid":1,"hostname":"282aa4a33ae4","message_id":435,"from":{"id":1643570542,"is_bot":false,"first_name":"XXXX","username":"XXXX","language_code":"zh-hans"},"chat":{"id":1643570542,"first_name":"XXXX","username":"XXXX","type":"private"},"date":1613572795,"text":"/deactivate 1","entities":[{"offset":0,"length":11,"type":"bot_command"}]}
python-agent_1  | [INFO] forwarder.py:34 -- Private Message Received
python-agent_1  | [INFO] forwarder.py:40 -- Message : Redirection deactivated [1]

> node-bot_1      | Activating redirection
node-bot_1      | {"level":30,"time":1613572727228,"pid":1,"hostname":"282aa4a33ae4","message_id":434,"from":{"id":1643570542,"is_bot":false,"first_name":"XXXX","username":"XXXXX","language_code":"zh-hans"},"chat":{"id":1643570542,"first_name":"XXXX","username":"XXXXX","type":"private"},"date":1613572726,"text":"/activate 1","entities":[{"offset":0,"length":9,"type":"bot_command"}]}
python-agent_1  | [INFO] server.py:82 -- [/getentity] :: Entity Name 1244800585
python-agent_1  | [2021-02-17 14:38:47,249] INFO in server: [/getentity] :: Entity Name 1244800585
python-agent_1  | [ERROR] server.py:87 -- Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7facafd6d0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
python-agent_1  | [2021-02-17 14:38:47,363] ERROR in server: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7facafd6d0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

ERROR: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7facafd6d0>.

The problem is that I'm pulling the latest and redeploying newly appeared

About filter: 
My previous test found that messages containing emojy could not be accurately filtered. (About two weeks ago)
Unfortunately there are no new tests, because my bot is not working now.

I hope to get your help, thank you.

**Comment by adityathebe** [comment]
This /activate and /deactivate commands should be passed a number not a string. 

I'll fix this bug later but for now you can just use the redirection id

**Comment by adityathebe** [comment]
> I'll fix this bug later but for now you can just use the redirection id

Fixed 3b4568b

**Comment by funnyxing** [comment]
Sorry I didn't make it clear

The problem I want to express is that the /activate command cannot activate the existing redirection id
I only have one redirection id[1], but if I enter “/activate 1” the log will produce an error

```
python-agent_1 | [ERROR] server.py:87 -- Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7facafd6d0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
python-agent_1 | [2021-02-17 14:38:47,363] ERROR in server: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7facafd6d0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
```

I tried to modify, but I did not succeed
It seems to be related to activateRedirection.js
Now I cannot activate any ID with /activate

Or you can teach me how to modify the /add command to activate redirection by default

**Comment by adityathebe** [comment]
It's possible that you have the wrong username

**Comment by funnyxing** [comment]
How to check, I have not encountered this problem before and the bot is used normally
This error occurred after I pulled the new warehouse and deployed it

**Comment by adityathebe** [comment]
You probably nuked the db after adding the redirection. 

Please remove the redirection with the command `/remove 1` and then re add the redirection with `/add` and then try to activate it.

**Comment by funnyxing** [comment]
No work
Same error
How to modify the /add command to activate redirection by default

**Comment by adityathebe** [comment]
Would you mind sharing the `/add` command you used so I can take a closer look ?

> How to modify the /add command to activate redirection by default
Not possible at the moment

**Comment by funnyxing** [comment]
![Snipaste_2021-02-21_16-30-22](https://user-images.githubusercontent.com/42426015/108619804-37fee200-7462-11eb-99d4-3d520e9dfffd.png)

**Comment by adityathebe** [comment]
![image](https://user-images.githubusercontent.com/13419481/108619887-f5cca500-744f-11eb-8e68-f86799d1bf00.png)

It's working fine for me

**Comment by funnyxing** [comment]
Thank you for helping me
It may be a problem with my telegram account
