### ISSUE TITLE
Service telegram-forwarder-node-bot start failed.

### ISSUE THREAD

**Issue by onoc1yn** [adityathebe/telegramForwarder#23]
```
Error: Cannot find module '/usr/src/telegram-forwarder/bot/wait-for.sh'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
internal/modules/cjs/loader.js:638
    throw err;
```

**Comment by adityathebe** [comment]
Please make sure you have the latest version. Specifically, check if your local repo has the file `telegram-forwarder/bot/wait-for.sh`.

**Comment by onoc1yn** [comment]
Yes, I have tried delete `telegramForwarder` folder and re-clone the project.
[root@hosthost bot]# pwd
/root/telegramForwarder/bot
[root@somehost bot]# ls wait-for.sh
wait-for.sh

**Comment by adityathebe** [comment]
Did you rebuild the docker images ? 

https://github.com/adityathebe/telegramForwarder#things-to-keep-in-mind

**Comment by onoc1yn** [comment]
Thanks for help, I rebuild the image and works fine.

> Did you rebuild the docker images ?
> 
> https://github.com/adityathebe/telegramForwarder#things-to-keep-in-mind
