### ISSUE TITLE
Extended explanation for filters

### ISSUE THREAD

**Issue by JuezFenix** [adityathebe/telegramForwarder#31]
Please, can you explain where or how can filter forwarded messages please?

I see types, mimes, etc, but i dont see where to aply.

**Comment by JuezFenix** [comment]
Ok, i see that its a telegram command, can you please paste a list of available command on the bot please

**Comment by adityathebe** [comment]
Sorry for the lack of documentation. Haven't got time to work on this. This feature is really buggy so I'd use it with caution.

The command is

```
/filter <filter-type> <redirection-id> <on/off>
```

## Example:
```
/filter photo 1 on
```

![image](https://user-images.githubusercontent.com/13419481/110971518-14ed9100-8383-11eb-8ffb-e54932ec7d9c.png)
