### ISSUE TITLE
error: You are not registered. Please send /start to register

### ISSUE THREAD

**Issue by s-ahmadzadeh** [adityathebe/telegramForwarder#32]
when I want to use bot as explained in help. but it shows an error that says: You are not registered. Please send /start to register
1. /start 
Welcome to MultiFeed Bot! 🔥
Send /help to get usage instructions
2. /help
3./add @es_channel1 @es_channel2
![Capture](https://user-images.githubusercontent.com/10596345/111044346-3f138180-845d-11eb-9205-6997fad32498.JPG)

**Comment by adityathebe** [comment]
For whatever reason that I am unaware of, telegram sometimes return a different user id. 

The user ID saved to your database is different than what you have now. 

A quick fix would be to delete your user from the database.

**Comment by computeronix** [comment]
I was encountering this too and after investigating, the users table was blank when I would issue /start from my test TG user account. No errors appeared.

The problem is if the username is blank then the program doesn't insert anything into the users table

workaround: add a username

however this will want to be reviewed for users that don't want to add a username to their TG account

**Comment by adityathebe** [comment]
Thank you

Fixed here: https://github.com/adityathebe/telegramForwarder/commit/bbee21eeecd9d02b426f47690a8479122ebd4660

**Comment by ruimartins21** [comment]
Does anyone know I can get the source link?
Because I'm trying to find the link of the private group that I'm in, and as I'm not the administrator I cant see the link.

Source : link to the channel to forward messages FROM(no admin permissions required)

**Comment by adityathebe** [comment]
> Does anyone know I can get the source link?
> Because I'm trying to find the link of the private group that I'm in, and as I'm not the administrator I cant see the link.
> 
> Source : link to the channel to forward messages FROM(no admin permissions required)

https://github.com/adityathebe/telegramForwarder/issues/36
