### ISSUE TITLE
where do you get TG_API_KEY from 

### ISSUE THREAD

**Issue by sachinbhatia4** [adityathebe/telegramForwarder#33]
ID and Hash ID are on https://my.telegram.org/apps
how to get TG_API_KEY

**Comment by adityathebe** [comment]
Can you share the steps that you've tried ?

**Comment by sachinbhatia4** [comment]
Trying to create .env file with below parameters  , but on https://my.telegram.org/auth?to=apps , i only see API_ID and Hash_ID , not sure if API_KEY is mandatory and where to find it from 
TG_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TG_API_ID=XXXX
TG_HASH_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TG_BOT_USERNAME=@XXXXXXXXXXXXXXXXXbot

**Comment by sachinbhatia4** [comment]
is it the Bot key

**Comment by adityathebe** [comment]
Yes, It is the bot key. You can get it by message t.me/botfather
