### ISSUE TITLE
[Request] Modify message before posting in the new channel

### ISSUE THREAD

**Issue by compunerd4** [adityathebe/telegramForwarder#34]
Will it be possible to add a feature to modify the message once you pull it and before you submit it?

Example:

1. Source channel message / content is pulled
2. We modify it by adding a link to our channel as a caption
3. The message is forwarded with our caption included

Some use cases:

- Adding a caption before it's posted
- Adding a link before it's posted
- Adding a new image on top of the album before it's posted 
- Renaming the file so it's "source" name + "new" name appended to it
- Adding watermarks to all  images forwarded (i'm achieving this by using a separate watermarking bot but it's manual)

I see there is a /transform option but I don't know the full capability and it's commented out in the code

**Comment by adityathebe** [comment]
I've added a basic transformation feature

You can 
- add new transformation for a given redirection using the `/transform` command
- list all the transformations of a given redirection using the `/transforms` command
- remove a transformation using the `/transformremove` command

**Comment by adityathebe** [comment]
Docs HERE

https://github.com/adityathebe/telegramForwarder/wiki/Text-Transformations
