### ISSUE TITLE
The key is not registered in the system (caused by ResolveUsernameRequest)

### ISSUE THREAD

**Issue by sodiumchloride2020** [adityathebe/telegramForwarder#35]
[2021-04-06 17:50:39,431] INFO in server: [/getentity] :: Entity Name @fastestdealsonline
python-agent_1  | [ERROR] server.py:87 -- The key is not registered in the system (caused by ResolveUsernameRequest)
python-agent_1  | [2021-04-06 17:50:39,594] ERROR in server: The key is not registered in the system (caused by ResolveUsernameRequest)
node-bot_1      | { err:
node-bot_1      |    Error: The key is not registered in the system (caused by ResolveUsernameRequest)
node-bot_1      |        at Promise (/usr/src/telegram-forwarder/bot/services/agent.js:107:17)
node-bot_1      |        at process._tickCallback (internal/process/next_tick.js:68:7) }
node-bot_1      | Error: The key is not registered in the system (caused by ResolveUsernameRequest)
node-bot_1      |     at Promise (/usr/src/telegram-forwarder/bot/services/agent.js:107:17)
node-bot_1      |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sodiumchloride2020** [comment]
![image](https://user-images.githubusercontent.com/69193224/113756703-59c0d980-972f-11eb-9752-bf235fe5b500.png)

**Comment by adityathebe** [comment]
https://github.com/adityathebe/telegramForwarder/issues/15
