### ISSUE TITLE
Can I use Channel ID? (example : 239239487)

### ISSUE THREAD

**Issue by comienzo2093** [adityathebe/telegramForwarder#36]
Hello, I would like to ask you how to set up using Channel id. Because I'm already in a private group, but I don't have the invite url.

Also, does @username mean the name of the channel? I am confused. I actually entered the name of the channel (Korean), but it didn't work.

Finally, thank you so much for the good script. You are a genius.

**Comment by adityathebe** [comment]
Yes, `@username` means username of channel/group/person ...

> I actually entered the name of the channel (Korean), but it didn't work.   

Can you post the error message so I can get a better idea?

**Comment by adityathebe** [comment]
If the agent telegram user is in a private group/channel and you know the id of that private group/channel then, yes, it's possible to create a redirection.

However, there's no command for that so you need to modify the database.

Here's a [guide in the Readme](https://github.com/adityathebe/telegramForwarder#access-database-from-the-docker-container) on how you can access the database.
