### ISSUE TITLE
Messeges Didnt forwarding

### ISSUE THREAD

**Issue by telegrambotdev** [adityathebe/telegramForwarder#4]
i am running this awsome app on docker.And bot is up.but after i set redirects,still no messeges are forwarding. ? i also activated the redirects.can you help me ?

**Comment by telegrambotdev** [comment]
@adityathebe Please fix it bro.Its an awsome bot..its amazing.you just need some final touch.

did you set any custom timing for message forwarding or something ? because the forward doesnt working for me 😢

**Comment by telegrambotdev** [comment]
This is the `error log`

![IMG_20200919_193330_037](https://user-images.githubusercontent.com/20116017/93669087-12367100-faaf-11ea-882e-524234a84055.jpg)

**Comment by adityathebe** [comment]
I am not able to say exactly what's causing this issue. But looks like a database issue.

**Comment by telegrambotdev** [comment]
> I am not able to say exactly what's causing this issue. But looks like a database issue.

so the current code is working fine for you ?

**Comment by adityathebe** [comment]
Yes, it's working fine for me

**Comment by telegrambotdev** [comment]
> Yes, it's working fine for me

i am already running seperate postgres database on my server.so anyway to change bot  database url to that ? for testing ?

**Comment by adityathebe** [comment]
You could change that in the docker-compose.yml file

**Comment by telegrambotdev** [comment]
> You could change that in the docker-compose.yml file

so if i add my postgres database url in docker-compose.yml

environment:
      API_PORT: 3000
      TG_API_ID: '${TG_API_ID}'
      TG_HASH_ID: '${TG_HASH_ID}'
      DB_HOST:=postgres://UNAME:PWD@IP:PORT/telegram

is it work ? i want to add my database url

**Comment by telegrambotdev** [comment]
version: '3.1'

services:
  node-bot:
    build: ./bot
    image: telegram-forwarder-node-bot
    environment:
      AGENT_PORT: 3000
      AGENT_HOSTNAME: python-agent
      TG_API_KEY: '${TG_API_KEY}'
      DB_HOST: postgres-db
      NTBA_FIX_319: 1
    depends_on:
      - postgres-db
    volumes: 
      - './bot:/usr/src/telegram-forwarder/bot'

  python-agent:
    build: './agent'
    image: 'telegram-forwarder-python-agent'
    depends_on:
      - postgres-db
    environment:
      API_PORT: 3000
      TG_API_ID: '${TG_API_ID}'
      TG_HASH_ID: '${TG_HASH_ID}'
      DB_HOST: postgres-db
    ports:
      - '3000:3000'
    volumes:
      - './agent/session:/telegram-python-agent/session'

  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

**Comment by telegrambotdev** [comment]
> version: '3.1'
> 
> services:
> node-bot:
> build: ./bot
> image: telegram-forwarder-node-bot
> environment:
> AGENT_PORT: 3000
> AGENT_HOSTNAME: python-agent
> TG_API_KEY: '${TG_API_KEY}'
> DB_HOST: postgres-db
> NTBA_FIX_319: 1
> depends_on:
> - postgres-db
> volumes:
> - './bot:/usr/src/telegram-forwarder/bot'
> 
> python-agent:
> build: './agent'
> image: 'telegram-forwarder-python-agent'
> depends_on:
> - postgres-db
> environment:
> API_PORT: 3000
> TG_API_ID: '${TG_API_ID}'
> TG_HASH_ID: '${TG_HASH_ID}'
> DB_HOST: postgres-db
> ports:
> - '3000:3000'
> volumes:
> - './agent/session:/telegram-python-agent/session'
> 
> postgres-db:
> image: postgres:alpine
> environment:
> POSTGRES_PASSWORD: mysecretpassword
> volumes:
> - ./init.sql:/docker-entrypoint-initdb.d/init.sql
> ports:
> - '5432:5432'

can you modify this code here,to  make for adding my database url 


like

DATABASE_URL = my database url

**Comment by adityathebe** [comment]
I'd recommend you to stick with docker database.

**Comment by telegrambotdev** [comment]
> I'd recommend you to stick with docker database.

but dockerdatabase is keep showing this error.

`ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f5ff18a06a0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.`

so it may be show ,on other users too,thats why i am asking your help
