### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kysterics** [adityathebe/telegramForwarder#40]
I got the bot api, telegram api, cloned the repository, created a .env file in the root directory with all the info and ran `docker-compose up`.

It's running now but how do I set which chat to redirect and which to redirect to? I checked the bot I created but nothing's there.

I suspect I entirely skipped this step, if so, how can I achieve them specifically?
> Once you get the database, python agent and node server running

Don't know if this helps but I'm including some screenshots:

![image](https://user-images.githubusercontent.com/63026996/118212660-b4530100-b464-11eb-9e8b-4a32bc72b599.png)
![image](https://user-images.githubusercontent.com/63026996/118212068-92f21500-b464-11eb-9050-eda2ecd7961c.png)
![image](https://user-images.githubusercontent.com/63026996/118211717-7229bf80-b464-11eb-99b0-36b51f05f89b.png)

**Comment by adityathebe** [comment]
> It's running now but how do I set which chat to redirect and which to redirect to?

You do that by using the `/add` command.
![image](https://user-images.githubusercontent.com/13419481/118349863-0da95600-b573-11eb-8097-013ccfe05a64.png)

**Comment by kysterics** [comment]
> You do that by using the `/add` command.

Thanks for replying! Unfortunately my bot doesn't respond to any commands, I'm sure something's wrong in the way I'm setting it up but I could not pinpoint what it is exactly...

**Comment by adityathebe** [comment]
ah I see your logs now. You probably have an old copy of the source code (or your had already built the docker image with an old source)

First, please make sure you have the latest code. And when running docker-compose use the `--build` flag.

I'd recommend you start fresh.

> docker-compose down -v --remove-orphans
> docker-compose up --build


https://github.com/adityathebe/telegramForwarder#things-to-keep-in-mind

**Comment by kysterics** [comment]
https://pastebin.com/9qcCn5i3

Still, my bot isn't responding...

**Comment by adityathebe** [comment]
The issue is that your node bot is unable to connect to the database. Do you have this file `https://github.com/adityathebe/telegramForwarder/blob/master/bot/wait-for.sh` ?

**Comment by kysterics** [comment]
Ahhh... I do have to have the file, but maybe since I'm running this on windows it's acting weird.

**Comment by adityathebe** [comment]
This might help you. https://stackoverflow.com/a/56791772/6199444

**Comment by kysterics** [comment]
Thanks for the help. I tried changing the line endings to LF for both of the Dockerfile's but the same error appears.
Btw, I couldn't find a `docker-entrypoint.sh` file anywhere in my system, might be relevant...

**Comment by adityathebe** [comment]
Not the docker file but the script file `bot/wait-for.sh` needs to be changed.

> Btw, I couldn't find a docker-entrypoint.sh file anywhere in my system, might be relevant

That's file. That file is in the docker image.

**Comment by kysterics** [comment]
> Not the docker file but the script file `bot/wait-for.sh` needs to be changed.


Oh it works now! Thanks!

**Comment by adityathebe** [comment]
awesome !
