### ISSUE TITLE
Showing an error

### ISSUE THREAD

**Issue by 5642881033306112** [adityathebe/telegramForwarder#5]
Sir,
when i ran your code in docker it threws this error.
i think the bot cant write in the database,can you recheck the code ?

`ValueError: Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7f5ff18a06a0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.`

**Comment by telegrambotdev** [comment]
https://stackoverflow.com/questions/58911827/could-not-find-the-input-entity-for-telethon-tl-types-peeruser-object-at

yep.he is got exact error as like mine.
check the error here
