### ISSUE TITLE
What error is this ?

### ISSUE THREAD

**Issue by telegrambotdev** [adityathebe/telegramForwarder#8]
Do you have any idea to fix this ?

![IMG_20201003_102801_862](https://user-images.githubusercontent.com/20116017/94983727-3b510a00-0563-11eb-997a-3f6fd100ce26.jpg)

**Comment by adityathebe** [comment]
https://github.com/LonamiWebs/Telethon/issues/814

**Comment by telegrambotdev** [comment]
but i dont understand the point ? should i need to edit the code ?

**Comment by telegrambotdev** [comment]
> [LonamiWebs/Telethon#814](https://github.com/LonamiWebs/Telethon/issues/814)

but i dont understand the point ? should i need to edit the code ?
